### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by seannymurrs** [capnslipp/ChatGPT-iOS#2]
I'm getting the following build failed error when trying to build the app in Xcode.

`/Users/sean/Library/Mobile Documents/com~apple~CloudDocs/Downloads/ChatGPT-iOS-master/ChatGPT/Assets.xcassets:./AppIcon.appiconset/[ios][universal][1024x1024][][][][][][] The app icon set "AppIcon" references a file "AppIcon.svg", but that file does not have a valid extension.
`

**Comment by capnslipp** [comment]
Interesting.  When I set this up, I was surprised that Xcode took the SVG and auto-converted it to PNG during build, since SVGs aren’t officially supported.  But perhaps there’s more to it than that.

What OS & Xcode versions are you using?

**Comment by seannymurrs** [comment]
I'm running the macOS Ventura beta and whatever Xcode is on the AppStore. Sorry, I'm away from home currently, but I can check later to get specfic version numbers. I converted the svg to a png myself and replaced it in the project, and the build succeeded. I'm having a different issue involving signing in on the app, but I will create a separate issue for that one.

**Comment by capnslipp** [comment]
Hmm.  I'm not seeing issue with Ventura release (13.2.1) with either Xcode release (14.2) or 14.3 beta 1.  Currently downloading 14.3 beta 2— I hope Apple didn't axe SVG/PDF/vector capability for icons.  Might be a beta bug.

More specifically, I see the same log message as you, and have for a long time (this and other projects since vector support was added in Xcode 12), but it's a **warning** instead of an error.  E.G. My machine and GitHub's Action runner show:

`/Users/runner/work/ChatGPT-iOS/ChatGPT-iOS/ChatGPT/Assets.xcassets:./AppIcon.appiconset/[ios][universal][1024x1024][][][][][][]: warning: The app icon set "AppIcon" references a file "AppIcon.svg", but that file does not have a valid extension.`

https://github.com/capnslipp/ChatGPT-iOS/actions/runs/4328217801/jobs/7557669731#step:4:176

**Comment by capnslipp** [comment]
Decided to just replace the SVG with a PNG to appease the warning/error
