### ISSUE TITLE
why i use wkwebView open chatGPT login always hint ”We ran into an issue while signing you in,please take a break and try again soon.“

### ISSUE THREAD

**Issue by LivenChief** [capnslipp/ChatGPT-iOS#5]

**Comment by capnslipp** [comment]
Because OpenAI updated how their website works, and since this is just a simple wrapper for the website, the app broke.  Honestly, there's no purpose of this app anymore— there's an official ChatGPT app for iOS now, and plenty of 3rd party apps and open-source apps that are far better than this (for one, using the official OpenAI API).  This app was only ever a fun experiment to see if ChatGPT itself can write an app to access ChatGPT.
